# Generated by Django 3.2 on 2021-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = 'Post',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('title', models.CharField(max_length = 256)),
                ('created', models.DateTimeField(auto_now_add = True)),
                ('updated', models.DateTimeField(auto_now = True)),
                ('text', models.TextField()),
            ],
        ),
    ]
