# Generated by Django 3.2 on 2021-04-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Like',
            fields = [
                ('id', models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('created', models.DateTimeField(auto_now_add = True)),
                ('author',
                 models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL, to = settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'posts.post')),
            ],
            options = {
                'unique_together': {('post', 'author')},
            },
        ),
    ]
